version: '3.6'
services:
  ui:
    container_name: ui
    image: asoltys/silhouettes
    restart: on-failure
    ports:
      - '3000:3000'
  app:
    depends_on:
      - hbp
    container_name: silapp
    image: asoltys/silhouettes-server
    restart: on-failure
    environment:
      HASURA_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      COINOS_URL: '${COINOS_URL}'
      COINOS_TOKEN: '${COINOS_TOKEN}'
      HASURA_JWT: '${HASURA_GRAPHQL_JWT_SECRET}'
    volumes:
      - ./:/app
    network_mode: host
  postgres:
    container_name: silpostgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  hasura:
    container_name: silhasura
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_JWT_SECRET: '${HASURA_GRAPHQL_JWT_SECRET}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hbp:
    container_name: silhbp
    image: asoltys/hbp:latest
    depends_on:
      - 'hasura'
    ports:
      - '3400:3000'
    environment:
      HASURA_ENDPOINT: '${HASURA_ENDPOINT}'
      HASURA_GRAPHQL_ADMIN_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      JWT_ALGORITHM: '${JWT_ALGORITHM}'
      JWT_KEY: '${JWT_KEY}'
      AUTO_MIGRATE: "true"
      STORAGE_ENABLED: "false"
      SERVER_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      REDIRECT_URL_ERROR: http://localhost:3000
      REDIRECT_URL_SUCCESS: http://localhost:3000
      AUTO_ACTIVATE_NEW_USERS: "false"
      EMAILS_ENABLED: "true"
      VERIFY_EMAILS: "true"
      LOST_PASSWORD_ENABLED: "true"
      SMTP_HOST: '${SMTP_HOST}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_USER: '${SMTP_USER}'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_SENDER: '${SMTP_SENDER}'
      SMTP_SECURE: "true"
  liquid:
    image: asoltys/liquid:latest
    container_name: silliquid
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
      - ${LIQUID_BLOCK_PORT}:18602
      - ${LIQUID_TX_PORT}:18603
    volumes:
      - ./liquid:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: silelectrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./liquid:/config
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: silesplora-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
