version: '3.6'
services:
  coming:
    container_name: coming
    image: asoltys/silhouettes
    restart: on-failure
    ports:
      - '3001:3000'
    volumes:
      - ${HOME}/silhouettes:/silhouettes
    command: "node coming"
  ui:
    container_name: silui
    image: asoltys/silhouettes
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - ${HOME}/silhouettes:/silhouettes
  litecoin:
    volumes:
      - /mnt/disks/ltc/.litecoin:/config
    ports:
      - '9332:9332'
      - '19506:18506'
      - '19507:18507'
